backend:
  name: github
  repo: hathor-hua/helen
  branch: main
  base_url: https://raspy-snow-0605.hathorhua.workers.dev
  auth_endpoint: auth

locale: 'zh_Hant'

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "標籤", name: "tags", widget: "list", default: ["雜談"] }
      - { label: "摘要", name: "description", widget: "string", required: false }
      - { label: "封面圖片", name: "image", widget: "image", required: false }
      - { label: "內文", name: "body", widget: "markdown" }
